### ISSUE TITLE
Python 2.7

### ISSUE THREAD

**Issue by jmh530** [h3llrais3r/Deluge-PreventSuspendPlus#1]
It would be helpful if you provide a release that supports Python 2.7 Deluge. That is the version that is available on the main deluge website.

**Comment by h3llrais3r** [comment]
Please see https://github.com/h3llrais3r/Deluge-PreventSuspendPlus/releases/download/1.0/PreventSuspendPlus-1.0-py2.7.egg

The version I provided is the one for Python 2.7. :wink:

**Comment by jmh530** [comment]
Sorry. I meant provide 2.6 also. 2.6 is the version of deluge that is on my machine.

**Comment by h3llrais3r** [comment]
I don't have Python 2.6 currently running on my machine, but it's really easy to create the .egg yourself.
Just follow the instructions as listed [here](https://github.com/h3llrais3r/Deluge-PreventSuspendPlus/blob/master/INSTALL).

**Comment by jmh530** [comment]
Will do. Thanks for the recommendation. For some reason the normal PreventSuspend was not working, so hopefully this does.

**Comment by h3llrais3r** [comment]
Which OS are you running?

**Comment by jmh530** [comment]
Windows 10

**Comment by h3llrais3r** [comment]
It's normal that the old one wasn't running because it didn't have support for Windows :wink: 
I've created this new version with the support for Windows, and I'm running it for half a year now without problems on Windows 8.1. So I think it should also be working on Windows 10.
PS: why not upgrade your python version?

**Comment by jmh530** [comment]
I'm pretty new to deluge. I just recently gave up utorrent. I don't know
how it uses python. I just installed whatever was on the website.

I'm pretty sure I have Anaconda installed on my machine with python 3.4 or
3.5. I used to have python 2.7 with it, but I may formatted since then so I
can't remember without being at my machine.

You seem to be saying that if I update my python to 2.7, then the add-on
should work just fine? I wouldn't need to re-install deluge?

**Comment by h3llrais3r** [comment]
Which deluge version are you using? 
You have separate installers for Deluge for Python 2.6 and 2.7.
I'm using http://download.deluge-torrent.org/windows/py2.7/deluge-1.3.12-1-win32-py2.7-setup.exe with Python 2.7 and my plugin and it works fine.

**Comment by jmh530** [comment]
I will have to double-check when I get home from work, but if that's what
works for you, then I will try it. It's important that I get this plug-in
working.

**Comment by h3llrais3r** [comment]
If you don't have a good reason for using 2.6 (f.e. another program that can't use 2.7) I would advise upgrading.
Let me know if it works for you, will you?
If you decide to build the .egg file for Python 2.6, please also share it and I'll upload it here :+1:

**Comment by jmh530** [comment]
It works.

I hadn't noticed the Python 2.7 folder I guess when I originally downloaded
it.

**Comment by h3llrais3r** [comment]
I'm glad to hear it's working now :wink:
