### ISSUE TITLE
Plugin seems to not work

### ISSUE THREAD

**Issue by derei** [h3llrais3r/Deluge-PreventSuspendPlus#2]
Windows 7 will go into sleep mode even with the plugin set to Always prevent suspend.
It doesn't do the intended job, basically.
Deluge 1.3.15

**Comment by h3llrais3r** [comment]
Saying that is doesn't do the job, without proof, will not resolve it either...
I'm using this for quite some years now on windows, and it does work.
Perhaps you can start with providing some logs of what's happening on your deluge instance?

EDIT: did you also try the other setting 'downloading or seeding'? Or is it only the 'always' option that you have problems with?

**Comment by derei** [comment]
I was expecting the plugin to override Windows sleep policies, but it didn't.
Laptop was set to go to sleep when lid was closed, but the plugin did not override it. I had to disable the feature, in order to keep laptop awake with deluge running.
Or, if this plugin is not meant to override such hardware commands, it should specify in its description what it does and what are the limitations.

**Comment by h3llrais3r** [comment]
I don't think that any software can override a hardware sleep/shutdown of a pc...
If you close your lid, click the shutdown/sleep button or click on restart, you have the intention of triggering that action and nothing can prevent that.
So as you are saying now, the plugin does work, but apparently not as you want it to work...
Feel free to fork it and update it to your own needs. 😉
If the description is also not clear enough, please also create a PR for this.
